openapi: "3.0.2"

info:
  version: "0.0.1"
  title: VNG - Single Digital Gateway (SDG)
  description: Deze toepassing faciliteert bevragingen van Producten binnen de SDG verordening

servers:
  - description: Development
    url: http://localhost:8081/rest/v1
  - description: Test
    url: https://sdg-test.lostlemon.nl/rest/v1

paths:
  /sdgproducten:
    put:
      tags:
        - SDG Producten
      summary: Voegt een SdgProduct toe of wijzigt de gegevens van een SdgProduct
      description: Het toevoegen of wijzigen van een SdgProduct gegevens aan de invoervoorziening in een bepaalde taal
      operationId: putSdgProduct
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SdgProduct'
      responses:
        200:
          description: Sdg Product gegevens succesvol bijgewerkt
        400:
          $ref: '#/components/responses/400BadRequest'

  /sdgproducten/{identifier}:
    parameters:
      - $ref: '#/components/parameters/identifier'
    get:
      tags:
        - SDG Producten
      summary: Het ophalen van een SDG Product
      description: Het ophalen van een SDG Product aan de hand van de unieke productnaam, de taal en de overheidsorganisatie.
      operationId: getSdgProduct
      parameters:
        - $ref: '#/components/parameters/Taal'
        - $ref: '#/components/parameters/OWMSIdentifier'
      responses:
        200:
          description: Zoekactie geslaagd
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/SdgProduct'
        404:
          $ref: '#/components/responses/404NotFound'
  /sdgproducten/{owmsIdentifier}:
    parameters:
      - $ref: '#/components/parameters/OWMSIdentifier'
      - $ref: '#/components/parameters/Taal'
    get:
      tags:
        - SDG Producten
      summary: Het ophalen van alle SDG Producten voor een overheidsorganisatie in een gegeven taal
      description: Het ophalen van een SDG Product aan de hand van de overheidsorganisatie en de taal.
      operationId: getSdgProducten
      responses:
        200:
          description: Ophalen geslaagd
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SdgProduct'
        404:
          $ref: '#/components/responses/404NotFound'

  /organisatie/{identifier}:
    parameters:
      - $ref: '#/components/parameters/OWMSIdentifier'
      - $ref: '#/components/parameters/Taal'
    get:
      tags:
        - Overheidsorganisaties
      summary: Het ophalen van gegevens van een overheidsorganisaties zoals bekend binnen de owms
      description: Het ophalen van gegevens van een overheidsorganisaties zoals bekend binnen de owms
      operationId: getOrganisatie
      responses:
        200:
          description: Ophalen geslaagd
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Organisatie'
        404:
          $ref: '#/components/responses/404NotFound'
components:
  parameters:
    identifier:
      description: de identifier van het Product
      in: path
      name: identifier
      required: true
      schema:
        type: string
    Taal:
      description: de gevraagde taal
      in: header
      name: taal
      required: true
      schema:
        type: string
    OWMSIdentifier:
      description: de identifier van de overheidsorganisatie
      in: header
      name: owmsIdentifier
      required: true
      schema:
        type: string
    owms:
      in: path
      name: owms
      required: true
      schema:
        type: string

  responses:
    404NotFound:
      description: Product(en) niet gevonden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    400BadRequest:
      description: bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
    401Unauthorized:
      description: Niet geautoriseerd
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

  schemas:
    Errors:
      type: array
      items:
        $ref: '#/components/schemas/Error'

    Error:
      type: object
      properties:
        code:
          $ref: '#/components/schemas/ErrorCode'
        parameter:
          type: string
        message:
          type: string
      required:
        - code
        - message
    SdgProduct:
      description: een product gedefinieerd volgens de SDG verordening
      type: object
      properties:
        taal:
          description: de taak waarin de dienst geleverd wordt
          type: string
        productNaam:
          description: de naam volgens de Nationale Portalen
          type: string
        samenvatting:
          description: de samenvatting volgens de Nationale Portalen
          type: string
        laatsteWijziging:
          description: de datum waarop het product voor het laatst gecontroleerd is
          type: string
        uniformProduct:
            $ref: '#/components/schemas/UniformProduct'
        productInformatie:
              $ref: '#/components/schemas/ProductInformatie'
        procedureInformatie:
              $ref: '#/components/schemas/ProcedureInformatie'

    ErrorCode:
      type: string
      enum:
        - PRODUCT_NOT_FOUND
        - PARAMETER_REQUIRED
        - PARAMETER_LENGTH
        - INVALID_MUNICIPALITY_CODE
        - NOT_AUTHORIZED
        - UNEXPECTED_ERROR
    SdgType:
      type: object
      properties:
        code:
          type: string
        titel:
          type: string
    InformationArea:
      type: object
      properties:
        code:
          type: string
        titel:
          type: string
        sdgType:
              $ref: '#/components/schemas/SdgType'
    Policy:
      type: object
      properties:
        code:
          type: string
        titel:
          type: string
        informationArea:
              $ref: '#/components/schemas/InformationArea'
    OWMSIdentifier:
      type: object
      properties:
        identifier:
          type: string
        prefLabel:
          type: string
    ProductInformatie:
      type: object
      properties:
        bevoegdGezag:
          $ref: '#/components/schemas/Organisatie'
        productNaam:
          type: string
        beschrijving:
          description: de beschrijving volgens de lokale authoriteit
          type: string
        lokaties:
          $ref: '#/components/schemas/Lokaties'
        laatsteWijziging:
          type: string
    UniformProduct:
      description: een product gedefinieerd van de UPN
      type: object
      properties:
        identifier:
          description: de unieke identifier van het product
          type: string
        prefLabel:
          description: de naam volgens de Nationale Portalen
          type: string
        grondslaglabel:
          type: string
        grondslaglink:
          type: string
        datumLaatsteCheck:
          description: de datum waarop het product voor het laatst gecontroleerd is
          type: string
          format: date
        policy:
          $ref: '#/components/schemas/Policy'
    ProcedureInformatie:
      type: object
      properties:
        stappen:
          type: string
        uitzonderingen:
          type: string
        authenticatie_Vereisten:
          type: string
        identificatie_Vereisten:
          type: string
        handtekening_Vereisten:
          type: string
        bewijs_Type:
          type: string
        bewijs_Formaat:
          type: string
        bezwaar:
          type: string
        beroep:
          type: string
        kosten:
          type: string
        betaalwijzen:
          type: string
        deadlines:
          type: string
        geen_Reactie:
          type: string
        vertragingen:
          type: string
        laatsteWijziging:
          type: string
        eigenaar_Procedure:
          $ref: '#/components/schemas/Organisatie'
    Organisatie:
      type: object
      properties:
        owmsIdentifier:
          type: string
        owmsPreflabel:
          type: string
        lokaties:
          $ref: '#/components/schemas/Lokaties'
    Lokaties:
      type: array
      items:
        $ref: '#/components/schemas/Lokatie'
    Lokatie:
      type: object
      properties:
        adres:
          type: string
        openingstijden:
          type: string
        contact:
          $ref: '#/components/schemas/Contact'
    Contact:
      type: object
      properties:
        email:
          type: string
        site:
          type: string
        telefoon:
          type: string